version: '3'

networks:
  app-network:
    driver: bridge


services:
  frontend:
    build:
      context: ./proyecto-frontend-dam
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    networks:
      - app-network
  
  backend:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./proyecto-backend-dam
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - database


  database:
    container_name: database
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hunkyDoryCode
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./proyecto-docs-dam/DDBB/IMPLEMENTACION/DDBB2.sql:/docker-entrypoint-initdb.d/ddbb.sql
      # - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "admin", "-proot"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

# volumes:
#   db-data:
#     driver: local
